"""Session storage: entry/record model, derived-state projection, and backends.

Python port of `packages/agent/src/harness/session/index.ts`. Re-exports the
Entry/Record model and query types (`types.py`), the session context
projection (`context.py`), the in-memory backend (`memory.py`), the `Session`
facade (`session.py`), and the JSONL v4 backend (`jsonl/`).

Search used to live here too. Upstream moved it to its own top-level module in
`refactor: search` (#7797); this port follows, so it is now `pi_agent.search`.
"""

from __future__ import annotations

from .context import (
    BRANCH_SUMMARY_PREFIX,
    BRANCH_SUMMARY_SUFFIX,
    COMPACTION_SUMMARY_PREFIX,
    COMPACTION_SUMMARY_SUFFIX,
    BranchSummaryMessage,
    CompactionSummaryMessage,
    ContextEntryTransform,
    ContextMessage,
    CustomEntryContextMessageProjector,
    SessionContext,
    SessionContextBuildOptions,
    SessionContextModel,
    build_context_entries,
    build_session_context,
    create_branch_summary_message,
    create_compaction_summary_message,
    default_context_entry_transform,
    session_entry_to_context_messages,
)
from .jsonl import (
    JsonlForkOptions,
    JsonlSessionCreateOptions,
    JsonlSessionListOptions,
    JsonlSessionMetadata,
    JsonlSessionRepo,
    JsonlSessionRepoOptions,
    JsonlV4Header,
)
from .memory import InMemorySessionRepo, InMemorySessionStorage
from .session import Session, assert_json_serializable
from .state import SessionMutation, SessionState
from .types import (
    ENTRY_TYPES,
    OPERATION_KINDS,
    RECORD_TYPES,
    AbortRequestedRecord,
    ActiveToolsEntry,
    BranchBounds,
    BranchSummaryEntry,
    CompactionEntry,
    CompactionIntent,
    CompactionReason,
    CustomEntry,
    Entry,
    EntryCursor,
    EntryOrder,
    EntryQuery,
    ForkOptions,
    IdGenerator,
    JsonValue,
    LanePointer,
    LaneRecord,
    LogEntryItem,
    LogItem,
    LogLabelFactItem,
    LogLaneItem,
    LogNameFactItem,
    LogOptions,
    LogRecordItem,
    MessageEntry,
    ModelChangeEntry,
    NavigationIntent,
    NewRecord,
    OperationFinishedError,
    OperationFinishedRecord,
    OperationIntent,
    OperationStartedRecord,
    ProvisionedEntry,
    QueueCancelledRecord,
    QueueEnqueuedRecord,
    RecordQuery,
    RunIntent,
    SessionCreateOptions,
    SessionError,
    SessionErrorCode,
    SessionErrorCodeLiteral,
    SessionMetadata,
    SessionRepo,
    SessionStats,
    SessionStopReason,
    SessionStorage,
    SessionTree,
    StepAttemptRecord,
    ThinkingLevelEntry,
    ToolStartedRecord,
    UsageCause,
    UsageRecord,
    WriteDeferredRecord,
)

__all__ = [
    "BRANCH_SUMMARY_PREFIX",
    "BRANCH_SUMMARY_SUFFIX",
    "COMPACTION_SUMMARY_PREFIX",
    "COMPACTION_SUMMARY_SUFFIX",
    "ENTRY_TYPES",
    "OPERATION_KINDS",
    "RECORD_TYPES",
    "AbortRequestedRecord",
    "ActiveToolsEntry",
    "BranchBounds",
    "BranchSummaryEntry",
    "BranchSummaryMessage",
    "CompactionEntry",
    "CompactionIntent",
    "CompactionReason",
    "CompactionSummaryMessage",
    "ContextEntryTransform",
    "ContextMessage",
    "CustomEntry",
    "CustomEntryContextMessageProjector",
    "Entry",
    "EntryCursor",
    "EntryOrder",
    "EntryQuery",
    "ForkOptions",
    "IdGenerator",
    "InMemorySessionRepo",
    "InMemorySessionStorage",
    "JsonValue",
    "JsonlForkOptions",
    "JsonlSessionCreateOptions",
    "JsonlSessionListOptions",
    "JsonlSessionMetadata",
    "JsonlSessionRepo",
    "JsonlSessionRepoOptions",
    "JsonlV4Header",
    "LanePointer",
    "LaneRecord",
    "LogEntryItem",
    "LogItem",
    "LogLabelFactItem",
    "LogLaneItem",
    "LogNameFactItem",
    "LogOptions",
    "LogRecordItem",
    "MessageEntry",
    "ModelChangeEntry",
    "NavigationIntent",
    "NewRecord",
    "OperationFinishedError",
    "OperationFinishedRecord",
    "OperationIntent",
    "OperationStartedRecord",
    "ProvisionedEntry",
    "QueueCancelledRecord",
    "QueueEnqueuedRecord",
    "RecordQuery",
    "RunIntent",
    "Session",
    "SessionContext",
    "SessionContextBuildOptions",
    "SessionContextModel",
    "SessionCreateOptions",
    "SessionError",
    "SessionErrorCode",
    "SessionErrorCodeLiteral",
    "SessionMetadata",
    "SessionMutation",
    "SessionRepo",
    "SessionState",
    "SessionStats",
    "SessionStopReason",
    "SessionStorage",
    "SessionTree",
    "StepAttemptRecord",
    "ThinkingLevelEntry",
    "ToolStartedRecord",
    "UsageCause",
    "UsageRecord",
    "WriteDeferredRecord",
    "assert_json_serializable",
    "build_context_entries",
    "build_session_context",
    "create_branch_summary_message",
    "create_compaction_summary_message",
    "default_context_entry_transform",
    "session_entry_to_context_messages",
]
