"""Tests for `pi_agent.harness.session.jsonl.codec`.

The most important property this module has to hold is wire compatibility
with the TypeScript `pi` CLI: a `.jsonl` session log written by TypeScript
must decode correctly here, and anything this port writes must be decodable
by TypeScript. The fixtures below are hand-written with TypeScript-style
camelCase keys (not generated by the Python encoder) so a regression in the
decoder's field-name mapping can't hide behind a matching bug in the encoder.
"""

from __future__ import annotations

import json

import pytest
from pi_ai.types import (
    AssistantMessage,
    AssistantMessageDiagnostic,
    Cost,
    DeferredHandle,
    ImageContent,
    TextContent,
    ThinkingContent,
    ToolCall,
    ToolResultMessage,
    Usage,
    UserMessage,
)

from pi_agent.harness.session.jsonl.codec import (
    decode_entry,
    decode_header,
    decode_mutation,
    decode_provisioned_entry,
    decode_record,
    encode_header,
    encode_mutation,
    entry_to_wire,
    metadata_from_header,
    parse_header,
    parse_mutation,
    provisioned_entry_to_wire,
    record_to_wire,
)
from pi_agent.harness.session.jsonl.errors import JsonlDecodeError
from pi_agent.harness.session.jsonl.types import JsonlV4Header
from pi_agent.harness.session.state import (
    EntryMutation,
    LabelFactMutation,
    LaneMutation,
    NameFactMutation,
    RecordMutation,
)
from pi_agent.harness.session.types import (
    AbortRequestedRecord,
    ActiveToolsEntry,
    BranchSummaryEntry,
    CompactionEntry,
    CompactionIntent,
    CustomEntry,
    MessageEntry,
    ModelChangeEntry,
    NavigationIntent,
    OperationFinishedError,
    OperationFinishedRecord,
    OperationStartedRecord,
    QueueCancelledRecord,
    QueueEnqueuedRecord,
    RunIntent,
    StepAttemptRecord,
    ThinkingLevelEntry,
    ToolStartedRecord,
    UsageRecord,
    WriteDeferredRecord,
)

# --------------------------------------------------------------------------
# Header: hand-written TS-style fixtures
# --------------------------------------------------------------------------


def test_decodes_hand_written_header_line() -> None:
    line = (
        '{"kind":"header","version":4,"id":"sess-1","createdAt":1700000000000,'
        '"cwd":"/home/user/project","parentSessionId":"sess-0",'
        '"metadata":{"origin":"cli"}}'
    )
    header = decode_header(line)
    assert header.id == "sess-1"
    assert header.created_at == 1700000000000
    assert header.cwd == "/home/user/project"
    assert header.parent_session_id == "sess-0"
    assert header.legacy_parent_session_path is None
    assert header.metadata == {"origin": "cli"}


def test_decodes_hand_written_header_with_legacy_parent_path() -> None:
    line = (
        '{"kind":"header","version":4,"id":"sess-2","createdAt":1,'
        '"cwd":"/tmp/x","legacyParentSessionPath":"/old/sessions/parent.jsonl"}'
    )
    header = decode_header(line)
    assert header.parent_session_id is None
    assert header.legacy_parent_session_path == "/old/sessions/parent.jsonl"


def test_decodes_minimal_hand_written_header() -> None:
    line = '{"kind":"header","version":4,"id":"sess-3","createdAt":0,"cwd":""}'
    header = decode_header(line)
    assert header.parent_session_id is None
    assert header.metadata is None


def test_rejects_header_with_both_parent_forms() -> None:
    line = (
        '{"kind":"header","version":4,"id":"sess-4","createdAt":0,"cwd":"",'
        '"parentSessionId":"a","legacyParentSessionPath":"b"}'
    )
    try:
        decode_header(line)
    except JsonlDecodeError:
        pass
    else:
        raise AssertionError("expected JsonlDecodeError")


def test_rejects_unsupported_header_version() -> None:
    line = '{"kind":"header","version":3,"id":"sess-5","createdAt":0,"cwd":""}'
    try:
        decode_header(line)
    except JsonlDecodeError:
        pass
    else:
        raise AssertionError("expected JsonlDecodeError")


def test_header_round_trips_through_encode_decode() -> None:
    header = JsonlV4Header(
        id="sess-rt",
        created_at=123,
        cwd="/a/b",
        parent_session_id="parent",
        metadata={"k": "v"},
    )
    line = encode_header(header)
    assert decode_header(line) == header


# --------------------------------------------------------------------------
# Mutations: hand-written TS-style fixtures
# --------------------------------------------------------------------------


def test_decodes_hand_written_message_entry_mutation() -> None:
    line = (
        '{"kind":"entry","lane":"main","type":"message","id":"e1",'
        '"message":{"role":"user","content":"hi","timestamp":1000},'
        '"parentId":null,"seq":1,"timestamp":1000}'
    )
    mutation = decode_mutation(line)
    assert isinstance(mutation, EntryMutation)
    assert mutation.lane == "main"
    entry = mutation.entry
    assert isinstance(entry, MessageEntry)
    assert entry.id == "e1"
    assert entry.parent_id is None
    assert entry.seq == 1
    assert entry.timestamp == 1000
    assert isinstance(entry.message, UserMessage)
    assert entry.message.content == "hi"


def test_decodes_hand_written_assistant_message_with_tool_call() -> None:
    line = (
        '{"kind":"entry","lane":"main","type":"message","id":"e2",'
        '"message":{"role":"assistant","api":"chat","provider":"anthropic",'
        '"model":"claude","content":[{"type":"text","text":"ok"},'
        '{"type":"toolCall","id":"call-1","name":"read","arguments":{"path":"a.py"}}],'
        '"usage":{"input":10,"output":5,"cacheRead":0,"cacheWrite":0,"totalTokens":15,'
        '"cost":{"input":0.1,"output":0.2,"cacheRead":0,"cacheWrite":0,"total":0.3}},'
        '"stopReason":"toolUse","timestamp":2000},'
        '"parentId":"e1","seq":2,"timestamp":2000}'
    )
    mutation = decode_mutation(line)
    assert isinstance(mutation, EntryMutation)
    entry = mutation.entry
    assert isinstance(entry, MessageEntry)
    assert entry.parent_id == "e1"
    message = entry.message
    assert isinstance(message, AssistantMessage)
    assert message.stop_reason == "toolUse"
    assert isinstance(message.content[0], TextContent)
    assert isinstance(message.content[1], ToolCall)
    assert message.content[1].arguments == {"path": "a.py"}
    assert message.usage.total_tokens == 15
    assert message.usage.cost.total == 0.3


def test_decodes_hand_written_tool_result_message() -> None:
    line = (
        '{"kind":"entry","lane":"main","type":"message","id":"e3",'
        '"message":{"role":"toolResult","toolCallId":"call-1","toolName":"read",'
        '"content":[{"type":"text","text":"file contents"}],"isError":false,'
        '"addedToolNames":["write"],"timestamp":3000},'
        '"parentId":"e2","seq":3,"timestamp":3000}'
    )
    mutation = decode_mutation(line)
    entry = mutation.entry
    assert isinstance(entry, MessageEntry)
    message = entry.message
    assert isinstance(message, ToolResultMessage)
    assert message.tool_call_id == "call-1"
    assert message.added_tool_names == ["write"]
    assert message.is_error is False


def test_decodes_hand_written_model_change_entry() -> None:
    line = (
        '{"kind":"entry","lane":"main","type":"model_change","id":"e4",'
        '"provider":"openai","modelId":"gpt-5","parentId":"e3","seq":4,"timestamp":4000}'
    )
    mutation = decode_mutation(line)
    entry = mutation.entry
    assert isinstance(entry, ModelChangeEntry)
    assert entry.provider == "openai"
    assert entry.model_id == "gpt-5"


def test_decodes_hand_written_custom_entry_without_data() -> None:
    line = '{"kind":"entry","type":"custom","id":"e5","customType":"note","parentId":null,"seq":5,"timestamp":5000}'
    mutation = decode_mutation(line)
    entry = mutation.entry
    assert isinstance(entry, CustomEntry)
    assert entry.custom_type == "note"
    assert entry.data is None
    # No explicit "lane" key on the wire line -> lane defaults to None (the
    # active lane at append time), matching TS's `lane?: string` being absent.
    assert mutation.lane is None


def test_decodes_hand_written_lane_mutation() -> None:
    line = '{"kind":"lane","seq":6,"lane":"main","leafId":"e5"}'
    mutation = decode_mutation(line)
    assert isinstance(mutation, LaneMutation)
    assert mutation.lane == "main"
    assert mutation.leaf_id == "e5"


def test_decodes_hand_written_name_fact_with_name_present() -> None:
    line = '{"kind":"fact","seq":7,"fact":"name","name":"My Session"}'
    mutation = decode_mutation(line)
    assert isinstance(mutation, NameFactMutation)
    assert mutation.name == "My Session"


def test_decodes_hand_written_name_fact_with_absent_key_clears_name() -> None:
    # TS writes `{ kind: "fact", seq, fact: "name" }` (key omitted, not
    # `name: null`) to mean "clear the session name". `JSON.stringify` drops
    # `undefined` values, so an absent key -- not an explicit `null` -- is the
    # wire representation of "no name".
    line = '{"kind":"fact","seq":8,"fact":"name"}'
    mutation = decode_mutation(line)
    assert isinstance(mutation, NameFactMutation)
    assert mutation.name is None


def test_rejects_name_fact_with_explicit_null_name() -> None:
    # TS's parser does `typeof value.name !== "string"` and rejects an
    # explicit `null` even though it accepts an absent key; verify this port
    # keeps that same asymmetry rather than silently accepting `null`.
    line = '{"kind":"fact","seq":9,"fact":"name","name":null}'
    try:
        decode_mutation(line)
    except JsonlDecodeError:
        pass
    else:
        raise AssertionError("expected JsonlDecodeError for explicit null name")


def test_decodes_hand_written_label_fact_mutation() -> None:
    line = '{"kind":"fact","seq":10,"fact":"label","targetId":"e5","label":"important"}'
    mutation = decode_mutation(line)
    assert isinstance(mutation, LabelFactMutation)
    assert mutation.target_id == "e5"
    assert mutation.label == "important"


def test_decodes_hand_written_usage_record_mutation() -> None:
    line = (
        '{"kind":"record","type":"usage","id":"r1","lane":"main",'
        '"usage":{"input":1,"output":2,"cacheRead":3,"cacheWrite":4,"totalTokens":10,'
        '"cost":{"input":0.01,"output":0.02,"cacheRead":0.03,"cacheWrite":0.04,"total":0.1}},'
        '"cause":"assistant","runId":"run-1","entryId":"e2","attempt":1,"stopReason":"stop",'
        '"seq":11,"timestamp":6000}'
    )
    mutation = decode_mutation(line)
    assert isinstance(mutation, RecordMutation)
    record = mutation.record
    assert isinstance(record, UsageRecord)
    assert record.cause == "assistant"
    assert record.run_id == "run-1"
    assert record.stop_reason == "stop"
    assert record.usage.total_tokens == 10
    assert record.usage.cost.total == 0.1


def test_decodes_hand_written_tool_started_record() -> None:
    line = (
        '{"kind":"record","type":"tool_started","id":"r2","lane":"main","runId":"run-1",'
        '"assistantEntryId":"e2","toolIndex":0,"toolCallId":"call-1","toolName":"read",'
        '"effectiveArgs":{"path":"a.py"},"resultEntryId":"e3","replay":"safe","seq":12,"timestamp":7000}'
    )
    mutation = decode_mutation(line)
    record = mutation.record
    assert record.type == "tool_started"
    assert record.tool_call_id == "call-1"
    assert record.effective_args == {"path": "a.py"}
    assert record.replay == "safe"


def test_rejects_malformed_json_line() -> None:
    try:
        decode_mutation("{not json")
    except JsonlDecodeError:
        pass
    else:
        raise AssertionError("expected JsonlDecodeError")


def test_rejects_unknown_mutation_kind() -> None:
    try:
        decode_mutation('{"kind":"bogus","seq":1}')
    except JsonlDecodeError:
        pass
    else:
        raise AssertionError("expected JsonlDecodeError")


# --------------------------------------------------------------------------
# Round-trip: encode then decode must reproduce the original value
# --------------------------------------------------------------------------


def test_message_entry_mutation_round_trips() -> None:
    entry = MessageEntry(
        id="e1",
        message=UserMessage(content="hello", timestamp=1000),
        parent_id=None,
        seq=1,
        timestamp=1000,
    )
    mutation = EntryMutation(entry=entry, lane="main")
    line = encode_mutation(mutation)
    decoded = decode_mutation(line)
    assert decoded == mutation


def test_assistant_message_with_all_optional_fields_round_trips() -> None:
    entry = MessageEntry(
        id="e2",
        message=AssistantMessage(
            api="chat",
            provider="anthropic",
            model="claude",
            content=[TextContent(text="hi"), ToolCall(id="c1", name="read", arguments={"a": 1})],
            usage=Usage(input=1, output=2, cache_read=3, cache_write=4, total_tokens=10, cost=Cost(total=1.5)),
            stop_reason="toolUse",
            response_model="claude-x",
            response_id="resp-1",
            timestamp=2000,
        ),
        parent_id="e1",
        seq=2,
        timestamp=2000,
    )
    mutation = EntryMutation(entry=entry, lane="main")
    line = encode_mutation(mutation)
    decoded = decode_mutation(line)
    assert decoded == mutation


def test_name_fact_clear_omits_key_on_wire_and_round_trips() -> None:
    mutation = NameFactMutation(seq=1, name=None)
    line = encode_mutation(mutation)
    payload = json.loads(line)
    assert "name" not in payload
    assert decode_mutation(line) == mutation


def test_name_fact_set_round_trips() -> None:
    mutation = NameFactMutation(seq=1, name="hello")
    line = encode_mutation(mutation)
    payload = json.loads(line)
    assert payload["name"] == "hello"
    assert decode_mutation(line) == mutation


def test_label_fact_clear_omits_key_on_wire_and_round_trips() -> None:
    mutation = LabelFactMutation(seq=1, target_id="e1", label=None)
    line = encode_mutation(mutation)
    payload = json.loads(line)
    assert "label" not in payload
    assert decode_mutation(line) == mutation


def test_custom_entry_without_lane_round_trips() -> None:
    entry = CustomEntry(id="e5", custom_type="note", data={"x": 1}, parent_id=None, seq=1, timestamp=1)
    mutation = EntryMutation(entry=entry, lane=None)
    line = encode_mutation(mutation)
    payload = json.loads(line)
    assert "lane" not in payload
    assert decode_mutation(line) == mutation


def test_header_with_no_optional_fields_round_trips() -> None:
    header = JsonlV4Header(id="s1", created_at=0, cwd="")
    line = encode_header(header)
    payload = json.loads(line)
    assert "parentSessionId" not in payload
    assert "legacyParentSessionPath" not in payload
    assert "metadata" not in payload
    assert decode_header(line) == header


# --------------------------------------------------------------------------
# Content blocks: every variant and every optional wire key
# --------------------------------------------------------------------------


def _entry_line(entry) -> dict:
    return json.loads(encode_mutation(EntryMutation(entry=entry, lane="main")))


def _assistant(content: list, **kwargs) -> AssistantMessage:
    return AssistantMessage(api="chat", provider="anthropic", model="claude", content=content, timestamp=2000, **kwargs)


def _round_trip_entry(entry):
    mutation = EntryMutation(entry=entry, lane="main")
    decoded = decode_mutation(encode_mutation(mutation))
    assert decoded == mutation
    return decoded.entry


def _round_trip_record(record):
    mutation = RecordMutation(record=record)
    decoded = decode_mutation(encode_mutation(mutation))
    assert decoded == mutation
    return decoded.record


def test_text_content_signature_uses_the_camel_case_wire_key() -> None:
    entry = MessageEntry(
        id="e1",
        message=_assistant([TextContent(text="hi", text_signature="sig")]),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    payload = _entry_line(entry)

    assert payload["message"]["content"][0] == {"type": "text", "text": "hi", "textSignature": "sig"}
    _round_trip_entry(entry)


def test_thinking_content_round_trips_with_signature_and_redaction() -> None:
    entry = MessageEntry(
        id="e1",
        message=_assistant([ThinkingContent(thinking="hmm", thinking_signature="tsig", redacted=True)]),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    payload = _entry_line(entry)

    assert payload["message"]["content"][0] == {
        "type": "thinking",
        "thinking": "hmm",
        "thinkingSignature": "tsig",
        "redacted": True,
    }
    _round_trip_entry(entry)


def test_thinking_content_omits_absent_optional_keys() -> None:
    entry = MessageEntry(
        id="e1", message=_assistant([ThinkingContent(thinking="hmm")]), parent_id=None, seq=1, timestamp=1
    )

    payload = _entry_line(entry)

    assert payload["message"]["content"][0] == {"type": "thinking", "thinking": "hmm"}
    _round_trip_entry(entry)


def test_image_content_uses_the_mime_type_wire_key() -> None:
    entry = MessageEntry(
        id="e1",
        message=UserMessage(content=[ImageContent(data="Zm9v", mime_type="image/png")], timestamp=1),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    payload = _entry_line(entry)

    assert payload["message"]["content"][0] == {"type": "image", "data": "Zm9v", "mimeType": "image/png"}
    _round_trip_entry(entry)


def test_tool_call_content_round_trips_thought_signature_and_namespace() -> None:
    entry = MessageEntry(
        id="e1",
        message=_assistant(
            [
                ToolCall(
                    id="c1",
                    name="read",
                    arguments={"path": "a.py", "nested": {"deep": [1, True, None]}},
                    thought_signature="thought",
                    namespace="mcp",
                )
            ]
        ),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    payload = _entry_line(entry)

    assert payload["message"]["content"][0] == {
        "type": "toolCall",
        "id": "c1",
        "name": "read",
        "arguments": {"path": "a.py", "nested": {"deep": [1, True, None]}},
        "thoughtSignature": "thought",
        "namespace": "mcp",
    }
    _round_trip_entry(entry)


def test_rejects_unknown_content_types() -> None:
    line = (
        '{"kind":"entry","lane":"main","type":"message","id":"e1",'
        '"message":{"role":"assistant","api":"chat","provider":"p","model":"m",'
        '"content":[{"type":"video","data":"x"}],"stopReason":"stop","timestamp":1},'
        '"parentId":null,"seq":1,"timestamp":1}'
    )

    with pytest.raises(JsonlDecodeError) as excinfo:
        decode_mutation(line)

    assert excinfo.value.kind == "schema"


def test_rejects_content_blocks_with_non_string_text() -> None:
    line = (
        '{"kind":"entry","lane":"main","type":"message","id":"e1",'
        '"message":{"role":"user","content":[{"type":"text","text":42}],"timestamp":1},'
        '"parentId":null,"seq":1,"timestamp":1}'
    )

    with pytest.raises(JsonlDecodeError):
        decode_mutation(line)


def test_refuses_to_encode_unsupported_content() -> None:
    class _Alien:
        type = "alien"

    entry = MessageEntry(id="e1", message=_assistant([_Alien()]), parent_id=None, seq=1, timestamp=1)

    with pytest.raises(TypeError):
        encode_mutation(EntryMutation(entry=entry, lane="main"))


def test_refuses_to_encode_non_json_native_tool_call_arguments() -> None:
    entry = MessageEntry(
        id="e1",
        message=_assistant([ToolCall(id="c1", name="read", arguments={"when": object()})]),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    with pytest.raises(TypeError):
        encode_mutation(EntryMutation(entry=entry, lane="main"))


# --------------------------------------------------------------------------
# Usage, cost, deferred handles and diagnostics
# --------------------------------------------------------------------------


def test_usage_round_trips_hourly_cache_writes_and_reasoning_tokens() -> None:
    usage = Usage(
        input=1,
        output=2,
        cache_read=3,
        cache_write=4,
        cache_write_1h=5,
        reasoning=6,
        total_tokens=21,
        cost=Cost(input=0.1, output=0.2, cache_read=0.3, cache_write=0.4, total=1.0),
    )
    entry = MessageEntry(
        id="e1", message=_assistant([], usage=usage, stop_reason="stop"), parent_id=None, seq=1, timestamp=1
    )

    payload = _entry_line(entry)

    assert payload["message"]["usage"] == {
        "input": 1,
        "output": 2,
        "cacheRead": 3,
        "cacheWrite": 4,
        "totalTokens": 21,
        "cost": {"input": 0.1, "output": 0.2, "cacheRead": 0.3, "cacheWrite": 0.4, "total": 1.0},
        "cacheWrite1h": 5,
        "reasoning": 6,
    }
    _round_trip_entry(entry)


def test_usage_omits_absent_optional_token_counts() -> None:
    entry = MessageEntry(id="e1", message=_assistant([]), parent_id=None, seq=1, timestamp=1)

    payload = _entry_line(entry)

    assert "cacheWrite1h" not in payload["message"]["usage"]
    assert "reasoning" not in payload["message"]["usage"]


def test_decodes_usage_without_a_cost_object() -> None:
    line = (
        '{"kind":"entry","lane":"main","type":"message","id":"e1",'
        '"message":{"role":"assistant","api":"chat","provider":"p","model":"m","content":[],'
        '"usage":{"input":1,"output":2},"stopReason":"stop","timestamp":1},'
        '"parentId":null,"seq":1,"timestamp":1}'
    )

    entry = decode_mutation(line).entry

    assert entry.message.usage.cost == Cost()
    assert entry.message.usage.cache_read == 0
    assert entry.message.usage.total_tokens == 0


def test_decodes_an_assistant_message_without_a_usage_key() -> None:
    line = (
        '{"kind":"entry","lane":"main","type":"message","id":"e1",'
        '"message":{"role":"assistant","api":"chat","provider":"p","model":"m","content":[],'
        '"stopReason":"stop","timestamp":1},"parentId":null,"seq":1,"timestamp":1}'
    )

    entry = decode_mutation(line).entry

    assert entry.message.usage == Usage()


def test_deferred_handle_round_trips_every_wire_key() -> None:
    handle = DeferredHandle(
        provider="openai",
        model_id="o3",
        api="responses",
        id="batch-1",
        expires_at=1700000000000,
        poll_after_ms=5000,
        data={"cursor": "abc"},
    )
    entry = MessageEntry(
        id="e1",
        message=_assistant([], deferred=handle, stop_reason="deferred"),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    payload = _entry_line(entry)

    assert payload["message"]["deferred"] == {
        "provider": "openai",
        "modelId": "o3",
        "api": "responses",
        "id": "batch-1",
        "expiresAt": 1700000000000,
        "pollAfterMs": 5000,
        "data": {"cursor": "abc"},
    }
    _round_trip_entry(entry)


def test_deferred_handle_omits_absent_optional_keys() -> None:
    entry = MessageEntry(
        id="e1",
        message=_assistant([], deferred=DeferredHandle(provider="openai", model_id="o3", api="responses", id="b")),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    payload = _entry_line(entry)

    assert payload["message"]["deferred"] == {
        "provider": "openai",
        "modelId": "o3",
        "api": "responses",
        "id": "b",
    }
    _round_trip_entry(entry)


def test_diagnostics_round_trip_with_and_without_detail() -> None:
    entry = MessageEntry(
        id="e1",
        message=_assistant(
            [],
            diagnostics=[
                AssistantMessageDiagnostic(kind="warning", message="slow", detail={"ms": 1200}, timestamp=9),
                AssistantMessageDiagnostic(kind="notice", message="retried", timestamp=10),
            ],
        ),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    payload = _entry_line(entry)

    assert payload["message"]["diagnostics"] == [
        {"kind": "warning", "message": "slow", "timestamp": 9, "detail": {"ms": 1200}},
        {"kind": "notice", "message": "retried", "timestamp": 10},
    ]
    _round_trip_entry(entry)


# --------------------------------------------------------------------------
# Messages: remaining optional fields and error paths
# --------------------------------------------------------------------------


def test_assistant_error_fields_round_trip() -> None:
    entry = MessageEntry(
        id="e1",
        message=_assistant(
            [],
            stop_reason="error",
            error_message="upstream exploded",
            raw_stop_reason="server_error",
            end_turn=False,
        ),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    payload = _entry_line(entry)

    assert payload["message"]["errorMessage"] == "upstream exploded"
    assert payload["message"]["rawStopReason"] == "server_error"
    assert payload["message"]["endTurn"] is False
    _round_trip_entry(entry)


def test_tool_result_details_and_usage_round_trip() -> None:
    entry = MessageEntry(
        id="e1",
        message=ToolResultMessage(
            tool_call_id="c1",
            tool_name="read",
            content=[TextContent(text="body")],
            details={"lines": 3, "paths": ["a.py"]},
            usage=Usage(input=1, output=1, total_tokens=2),
            added_tool_names=["write", "edit"],
            is_error=True,
            timestamp=3000,
        ),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    payload = _entry_line(entry)

    assert payload["message"]["details"] == {"lines": 3, "paths": ["a.py"]}
    assert payload["message"]["usage"]["totalTokens"] == 2
    assert payload["message"]["addedToolNames"] == ["write", "edit"]
    assert payload["message"]["isError"] is True
    _round_trip_entry(entry)


def test_tool_result_omits_absent_optional_keys() -> None:
    entry = MessageEntry(
        id="e1",
        message=ToolResultMessage(tool_call_id="c1", tool_name="read", content=[], is_error=False, timestamp=1),
        parent_id=None,
        seq=1,
        timestamp=1,
    )

    payload = _entry_line(entry)

    assert "details" not in payload["message"]
    assert "usage" not in payload["message"]
    assert "addedToolNames" not in payload["message"]


def test_rejects_unknown_message_roles() -> None:
    line = (
        '{"kind":"entry","lane":"main","type":"message","id":"e1",'
        '"message":{"role":"system","content":"nope","timestamp":1},'
        '"parentId":null,"seq":1,"timestamp":1}'
    )

    with pytest.raises(JsonlDecodeError) as excinfo:
        decode_mutation(line)

    assert excinfo.value.kind == "schema"


def test_message_entry_terminate_flag_round_trips() -> None:
    entry = MessageEntry(
        id="e1", message=UserMessage(content="stop", timestamp=1), terminate=True, parent_id=None, seq=1, timestamp=1
    )

    payload = _entry_line(entry)

    assert payload["terminate"] is True
    _round_trip_entry(entry)
    assert "terminate" not in _entry_line(
        MessageEntry(id="e2", message=UserMessage(content="go", timestamp=1), parent_id=None, seq=1, timestamp=1)
    )


# --------------------------------------------------------------------------
# Entry variants
# --------------------------------------------------------------------------


def test_thinking_level_entry_round_trips() -> None:
    entry = ThinkingLevelEntry(id="e1", thinking_level="high", parent_id="e0", seq=2, timestamp=5)

    payload = _entry_line(entry)

    assert payload["thinkingLevel"] == "high"
    _round_trip_entry(entry)


def test_active_tools_entry_round_trips() -> None:
    entry = ActiveToolsEntry(id="e1", active_tool_names=["read", "write"], parent_id=None, seq=1, timestamp=5)

    payload = _entry_line(entry)

    assert payload["activeToolNames"] == ["read", "write"]
    _round_trip_entry(entry)


def test_compaction_entry_round_trips_with_every_optional_field() -> None:
    entry = CompactionEntry(
        id="e1",
        summary="compacted history",
        retained_tail=[UserMessage(content="tail", timestamp=1), _assistant([TextContent(text="reply")])],
        tokens_before=4321,
        details={"readFiles": ["a.py"], "modifiedFiles": ["b.py"]},
        usage=Usage(input=1, output=2, total_tokens=3),
        parent_id="e0",
        seq=3,
        timestamp=7,
    )

    payload = _entry_line(entry)

    assert payload["summary"] == "compacted history"
    assert payload["tokensBefore"] == 4321
    assert [m["role"] for m in payload["retainedTail"]] == ["user", "assistant"]
    assert payload["details"] == {"readFiles": ["a.py"], "modifiedFiles": ["b.py"]}
    assert payload["usage"]["totalTokens"] == 3
    _round_trip_entry(entry)


def test_compaction_entry_omits_absent_optional_fields() -> None:
    entry = CompactionEntry(id="e1", summary="s", tokens_before=0, parent_id=None, seq=1, timestamp=1)

    payload = _entry_line(entry)

    assert "details" not in payload
    assert "usage" not in payload
    assert payload["retainedTail"] == []
    _round_trip_entry(entry)


def test_branch_summary_entry_round_trips() -> None:
    entry = BranchSummaryEntry(
        id="e1",
        from_id="e-abandoned",
        summary="explored the parser",
        details={"readFiles": ["a.py"], "modifiedFiles": []},
        usage=Usage(input=4, output=5, total_tokens=9),
        parent_id="e0",
        seq=2,
        timestamp=6,
    )

    payload = _entry_line(entry)

    assert payload["fromId"] == "e-abandoned"
    assert payload["summary"] == "explored the parser"
    assert payload["usage"]["totalTokens"] == 9
    _round_trip_entry(entry)


def test_branch_summary_entry_omits_absent_optional_fields() -> None:
    entry = BranchSummaryEntry(id="e1", from_id="e0", summary="s", parent_id=None, seq=1, timestamp=1)

    payload = _entry_line(entry)

    assert "details" not in payload
    assert "usage" not in payload
    _round_trip_entry(entry)


def test_custom_entry_omits_absent_data() -> None:
    entry = CustomEntry(id="e1", custom_type="note", parent_id=None, seq=1, timestamp=1)

    payload = _entry_line(entry)

    assert "data" not in payload
    _round_trip_entry(entry)


def test_entry_to_wire_carries_storage_assigned_fields() -> None:
    entry = CustomEntry(id="e1", custom_type="note", data=None, parent_id="e0", seq=9, timestamp=1234)

    payload = entry_to_wire(entry)

    assert payload["parentId"] == "e0"
    assert payload["seq"] == 9
    assert payload["timestamp"] == 1234
    assert decode_entry(payload, 9) == entry


def test_provisioned_entry_to_wire_omits_storage_assigned_fields() -> None:
    entry = CustomEntry(id="e1", custom_type="note", data={"a": 1})

    payload = provisioned_entry_to_wire(entry)

    assert "parentId" not in payload
    assert "seq" not in payload
    assert "timestamp" not in payload
    assert decode_provisioned_entry(payload) == entry


def test_rejects_entries_with_an_unknown_type() -> None:
    with pytest.raises(JsonlDecodeError) as excinfo:
        decode_mutation('{"kind":"entry","type":"telepathy","id":"e1","parentId":null,"seq":1,"timestamp":1}')

    assert excinfo.value.kind == "schema"


def test_rejects_entries_without_an_id() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation('{"kind":"entry","type":"custom","customType":"note","parentId":null,"seq":1,"timestamp":1}')


def test_rejects_custom_entries_without_a_custom_type() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation('{"kind":"entry","type":"custom","id":"e1","parentId":null,"seq":1,"timestamp":1}')


def test_rejects_model_change_entries_missing_wire_fields() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation(
            '{"kind":"entry","type":"model_change","id":"e1","provider":"openai","parentId":null,"seq":1,"timestamp":1}'
        )


def test_rejects_branch_summary_entries_without_a_from_id() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation(
            '{"kind":"entry","type":"branch_summary","id":"e1","summary":"s","parentId":null,"seq":1,"timestamp":1}'
        )


def test_rejects_entries_with_a_non_string_parent_id() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation(
            '{"kind":"entry","type":"custom","id":"e1","customType":"n","parentId":7,"seq":1,"timestamp":1}'
        )


def test_rejects_entries_with_a_negative_timestamp() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation(
            '{"kind":"entry","type":"custom","id":"e1","customType":"n","parentId":null,"seq":1,"timestamp":-1}'
        )


def test_rejects_entries_with_a_non_string_lane() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation(
            '{"kind":"entry","lane":5,"type":"custom","id":"e1","customType":"n","parentId":null,"seq":1,"timestamp":1}'
        )


def test_refuses_to_encode_an_unsupported_entry() -> None:
    class _Alien:
        type = "alien"
        id = "e1"

    with pytest.raises(TypeError):
        encode_mutation(EntryMutation(entry=_Alien(), lane="main"))


# --------------------------------------------------------------------------
# Operation intents
# --------------------------------------------------------------------------


def test_run_intent_round_trips_with_every_optional_field() -> None:
    record = OperationStartedRecord(
        id="run-1",
        lane="main",
        source_leaf_id="e0",
        intent=RunIntent(
            original_prompt=[UserMessage(content="do it", timestamp=1)],
            initial_messages=[CustomEntry(id="p1", custom_type="note", data={"x": 1})],
            system_prompt_override="be brief",
            resume_data={"cursor": "abc"},
        ),
        seq=1,
        timestamp=10,
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["intent"]["kind"] == "run"
    assert payload["intent"]["originalPrompt"][0]["content"] == "do it"
    assert payload["intent"]["initialMessages"][0] == {
        "type": "custom",
        "id": "p1",
        "customType": "note",
        "data": {"x": 1},
    }
    assert payload["intent"]["systemPromptOverride"] == "be brief"
    assert payload["intent"]["resumeData"] == {"cursor": "abc"}
    _round_trip_record(record)


def test_run_intent_omits_absent_optional_fields() -> None:
    record = OperationStartedRecord(
        id="run-1", lane="main", source_leaf_id=None, intent=RunIntent(), seq=1, timestamp=10
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["intent"] == {"kind": "run", "originalPrompt": [], "initialMessages": []}
    assert payload["sourceLeafId"] is None
    _round_trip_record(record)


def test_compaction_intent_round_trips() -> None:
    record = OperationStartedRecord(
        id="run-2",
        lane="main",
        source_leaf_id=None,
        intent=CompactionIntent(result_entry_id="e-result", custom_instructions="focus on files"),
        seq=1,
        timestamp=10,
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["intent"] == {
        "kind": "compaction",
        "resultEntryId": "e-result",
        "customInstructions": "focus on files",
    }
    _round_trip_record(record)


def test_navigation_intent_round_trips_with_every_optional_field() -> None:
    record = OperationStartedRecord(
        id="run-3",
        lane="main",
        source_leaf_id="e5",
        intent=NavigationIntent(
            target_id="e2",
            summarize=True,
            custom_instructions="short please",
            label="checkpoint",
            summary_entry_id="e-summary",
        ),
        seq=1,
        timestamp=10,
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["intent"] == {
        "kind": "navigation",
        "targetId": "e2",
        "summarize": True,
        "customInstructions": "short please",
        "label": "checkpoint",
        "summaryEntryId": "e-summary",
    }
    _round_trip_record(record)


def test_navigation_intent_round_trips_a_null_target() -> None:
    record = OperationStartedRecord(
        id="run-4",
        lane="main",
        source_leaf_id=None,
        intent=NavigationIntent(target_id=None, summarize=False),
        seq=1,
        timestamp=10,
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["intent"] == {"kind": "navigation", "targetId": None, "summarize": False}
    _round_trip_record(record)


def test_rejects_operation_started_records_without_an_intent_object() -> None:
    with pytest.raises(JsonlDecodeError) as excinfo:
        decode_mutation(
            '{"kind":"record","type":"operation_started","id":"r","lane":"main",'
            '"sourceLeafId":null,"seq":1,"timestamp":1}'
        )

    assert excinfo.value.kind == "schema"


def test_rejects_unknown_operation_kinds() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation(
            '{"kind":"record","type":"operation_started","id":"r","lane":"main","sourceLeafId":null,'
            '"intent":{"kind":"teleport"},"seq":1,"timestamp":1}'
        )


def test_refuses_to_encode_an_unsupported_intent() -> None:
    class _Alien:
        kind = "alien"

    record = OperationStartedRecord(id="r", lane="main", source_leaf_id=None, intent=_Alien(), seq=1, timestamp=1)

    with pytest.raises(TypeError):
        encode_mutation(RecordMutation(record=record))


# --------------------------------------------------------------------------
# Records
# --------------------------------------------------------------------------


def test_abort_requested_record_round_trips() -> None:
    payload = json.loads(
        encode_mutation(
            RecordMutation(record=AbortRequestedRecord(id="r", lane="main", run_id="run-1", seq=1, timestamp=2))
        )
    )

    assert payload["runId"] == "run-1"
    _round_trip_record(AbortRequestedRecord(id="r", lane="main", run_id="run-1", seq=1, timestamp=2))


def test_operation_finished_record_round_trips_with_an_error() -> None:
    record = OperationFinishedRecord(
        id="r",
        lane="main",
        run_id="run-1",
        outcome="failed",
        error=OperationFinishedError(code="stream_error", message="boom"),
        seq=1,
        timestamp=2,
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["outcome"] == "failed"
    assert payload["error"] == {"code": "stream_error", "message": "boom"}
    _round_trip_record(record)


def test_operation_finished_record_omits_an_absent_error() -> None:
    record = OperationFinishedRecord(id="r", lane="main", run_id="run-1", outcome="completed", seq=1, timestamp=2)

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert "error" not in payload
    _round_trip_record(record)


def test_rejects_operation_finished_records_without_a_run_id() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation(
            '{"kind":"record","type":"operation_finished","id":"r","lane":"main",'
            '"outcome":"completed","seq":1,"timestamp":1}'
        )


def test_step_attempt_record_round_trips() -> None:
    record = StepAttemptRecord(
        id="r",
        lane="main",
        run_id="run-1",
        step="compaction",
        attempt=2,
        result_entry_id="e-result",
        compaction_reason="threshold",
        seq=1,
        timestamp=2,
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["step"] == "compaction"
    assert payload["attempt"] == 2
    assert payload["resultEntryId"] == "e-result"
    assert payload["compactionReason"] == "threshold"
    _round_trip_record(record)


def test_step_attempt_record_omits_an_absent_compaction_reason() -> None:
    record = StepAttemptRecord(
        id="r", lane="main", run_id="run-1", step="assistant", attempt=0, result_entry_id="e", seq=1, timestamp=2
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert "compactionReason" not in payload
    _round_trip_record(record)


def test_tool_started_record_round_trips() -> None:
    record = ToolStartedRecord(
        id="r",
        lane="main",
        run_id="run-1",
        assistant_entry_id="e2",
        tool_index=1,
        tool_call_id="c1",
        tool_name="edit",
        effective_args={"path": "a.py", "replace": ["x", "y"]},
        result_entry_id="e3",
        replay="never",
        seq=1,
        timestamp=2,
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["assistantEntryId"] == "e2"
    assert payload["toolIndex"] == 1
    assert payload["effectiveArgs"] == {"path": "a.py", "replace": ["x", "y"]}
    assert payload["replay"] == "never"
    _round_trip_record(record)


def test_queue_enqueued_record_round_trips_with_and_without_a_run_id() -> None:
    with_run = QueueEnqueuedRecord(
        id="r",
        lane="main",
        queue="steer",
        target=MessageEntry(id="q1", message=UserMessage(content="steer me", timestamp=1)),
        run_id="run-1",
        seq=1,
        timestamp=2,
    )
    without_run = QueueEnqueuedRecord(
        id="r2",
        lane="main",
        queue="nextRun",
        target=CustomEntry(id="q2", custom_type="note"),
        seq=2,
        timestamp=3,
    )

    with_payload = json.loads(encode_mutation(RecordMutation(record=with_run)))
    without_payload = json.loads(encode_mutation(RecordMutation(record=without_run)))

    assert with_payload["queue"] == "steer"
    assert with_payload["runId"] == "run-1"
    assert "parentId" not in with_payload["target"]
    assert "runId" not in without_payload
    _round_trip_record(with_run)
    _round_trip_record(without_run)


def test_queue_cancelled_record_round_trips_with_and_without_a_run_id() -> None:
    with_run = QueueCancelledRecord(id="r", lane="main", entry_id="q1", run_id="run-1", seq=1, timestamp=2)
    without_run = QueueCancelledRecord(id="r2", lane="main", entry_id="q2", seq=2, timestamp=3)

    payload = json.loads(encode_mutation(RecordMutation(record=with_run)))

    assert payload["entryId"] == "q1"
    assert "runId" not in json.loads(encode_mutation(RecordMutation(record=without_run)))
    _round_trip_record(with_run)
    _round_trip_record(without_run)


def test_write_deferred_record_round_trips() -> None:
    record = WriteDeferredRecord(
        id="r",
        lane="main",
        run_id="run-1",
        target=MessageEntry(id="d1", message=_assistant([TextContent(text="deferred")], stop_reason="deferred")),
        seq=1,
        timestamp=2,
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["target"]["id"] == "d1"
    assert "seq" not in payload["target"]
    _round_trip_record(record)


def test_usage_record_round_trips_every_optional_field() -> None:
    record = UsageRecord(
        id="r",
        lane="main",
        usage=Usage(input=1, output=2, total_tokens=3),
        cause="tool",
        run_id="run-1",
        entry_id="e2",
        attempt=3,
        stop_reason="stop",
        tool_call_id="c1",
        details={"tool": "read"},
        seq=1,
        timestamp=2,
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["cause"] == "tool"
    assert payload["toolCallId"] == "c1"
    assert payload["details"] == {"tool": "read"}
    _round_trip_record(record)


def test_usage_record_omits_absent_optional_fields() -> None:
    record = UsageRecord(id="r", lane="main", usage=Usage(), cause="adjustment", seq=1, timestamp=2)

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert set(payload) == {"kind", "type", "id", "lane", "cause", "usage", "seq", "timestamp"}
    _round_trip_record(record)


def test_decodes_a_usage_record_without_a_usage_key() -> None:
    record = decode_mutation(
        '{"kind":"record","type":"usage","id":"r","lane":"main","cause":"hook","seq":1,"timestamp":2}'
    ).record

    assert record.usage == Usage()


def test_record_to_wire_carries_storage_assigned_fields() -> None:
    record = AbortRequestedRecord(id="r", lane="main", run_id="run-1", seq=4, timestamp=99)

    payload = record_to_wire(record)

    assert payload["seq"] == 4
    assert payload["timestamp"] == 99
    assert decode_record(payload, 4) == record


def test_rejects_records_with_an_unknown_type() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation('{"kind":"record","type":"telepathy","id":"r","lane":"main","seq":1,"timestamp":1}')


def test_rejects_records_without_a_lane() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation('{"kind":"record","type":"abort_requested","id":"r","runId":"run","seq":1,"timestamp":1}')


def test_rejects_tool_started_records_missing_required_ids() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation(
            '{"kind":"record","type":"tool_started","id":"r","lane":"main","runId":"run-1",'
            '"toolIndex":0,"toolCallId":"c1","toolName":"read","resultEntryId":"e3","replay":"safe",'
            '"seq":1,"timestamp":1}'
        )


def test_refuses_to_encode_an_unsupported_record() -> None:
    class _Alien:
        type = "alien"
        id = "r"
        lane = "main"
        seq = 1
        timestamp = 1

    with pytest.raises(TypeError):
        encode_mutation(RecordMutation(record=_Alien()))


# --------------------------------------------------------------------------
# Header validation, aliases and metadata projection
# --------------------------------------------------------------------------


def test_rejects_non_header_lines() -> None:
    with pytest.raises(JsonlDecodeError) as excinfo:
        decode_header('{"kind":"entry","version":4,"id":"s","createdAt":0,"cwd":""}')

    assert excinfo.value.kind == "schema"


def test_rejects_headers_that_are_not_json_objects() -> None:
    with pytest.raises(JsonlDecodeError) as excinfo:
        decode_header("[1,2,3]")

    assert excinfo.value.kind == "schema"


def test_rejects_header_lines_that_are_not_json() -> None:
    with pytest.raises(JsonlDecodeError) as excinfo:
        decode_header("{oops")

    assert excinfo.value.kind == "syntax"


def test_rejects_headers_with_a_non_string_parent_session_id() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_header('{"kind":"header","version":4,"id":"s","createdAt":0,"cwd":"","parentSessionId":7}')


def test_rejects_headers_with_a_non_string_legacy_parent_path() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_header('{"kind":"header","version":4,"id":"s","createdAt":0,"cwd":"","legacyParentSessionPath":7}')


def test_rejects_headers_with_non_object_metadata() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_header('{"kind":"header","version":4,"id":"s","createdAt":0,"cwd":"","metadata":["a"]}')


def test_rejects_headers_with_a_non_string_id() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_header('{"kind":"header","version":4,"id":7,"createdAt":0,"cwd":""}')


def test_rejects_headers_with_a_negative_created_at() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_header('{"kind":"header","version":4,"id":"s","createdAt":-1,"cwd":""}')


def test_parse_header_is_an_alias_for_decode_header() -> None:
    line = '{"kind":"header","version":4,"id":"s","createdAt":5,"cwd":"/x"}'

    assert parse_header(line) == decode_header(line)


def test_metadata_from_header_projects_header_and_filesystem_fields() -> None:
    header = JsonlV4Header(
        id="session",
        created_at=1700000000000,
        cwd="/workspace/project",
        legacy_parent_session_path="/sessions/missing-parent.jsonl",
        metadata={"owner": "agent"},
    )

    metadata = metadata_from_header(header, "/sessions/session.jsonl", 1700000000100)

    assert metadata.id == "session"
    assert metadata.created_at == 1700000000000
    assert metadata.cwd == "/workspace/project"
    assert metadata.path == "/sessions/session.jsonl"
    assert metadata.modified_at == 1700000000100
    assert metadata.source_format == 4
    assert metadata.parent_session_id is None
    assert metadata.legacy_parent_session_path == "/sessions/missing-parent.jsonl"
    assert metadata.metadata == {"owner": "agent"}


def test_header_round_trips_a_legacy_parent_path_and_nested_metadata() -> None:
    header = JsonlV4Header(
        id="legacy-child",
        created_at=1700000000001,
        cwd="/workspace/project",
        legacy_parent_session_path="/sessions/missing-parent.jsonl",
        metadata={"owner": "agent", "nested": {"enabled": True}, "values": [1, None, "two"]},
    )

    line = encode_header(header)

    assert line.endswith("\n")
    assert decode_header(line) == header


# --------------------------------------------------------------------------
# Mutation envelope: seq validation, aliases, framing
# --------------------------------------------------------------------------


def test_rejects_mutations_whose_seq_is_not_a_positive_integer() -> None:
    for seq in ("0", "-1", '"1"', "1.5", "true", "null"):
        with pytest.raises(JsonlDecodeError):
            decode_mutation(f'{{"kind":"lane","seq":{seq},"lane":"main","leafId":null}}')


def test_rejects_mutations_that_are_not_json_objects() -> None:
    with pytest.raises(JsonlDecodeError) as excinfo:
        decode_mutation('"just a string"')

    assert excinfo.value.kind == "schema"


def test_rejects_lane_mutations_with_a_non_string_leaf_id() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation('{"kind":"lane","seq":1,"lane":"main","leafId":7}')


def test_rejects_unknown_fact_types() -> None:
    with pytest.raises(JsonlDecodeError) as excinfo:
        decode_mutation('{"kind":"fact","seq":1,"fact":"colour","value":"blue"}')

    assert excinfo.value.kind == "schema"


def test_rejects_label_facts_with_an_explicit_null_label() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation('{"kind":"fact","seq":1,"fact":"label","targetId":"e1","label":null}')


def test_rejects_label_facts_without_a_target_id() -> None:
    with pytest.raises(JsonlDecodeError):
        decode_mutation('{"kind":"fact","seq":1,"fact":"label","label":"x"}')


def test_label_fact_with_an_absent_label_key_clears_the_label() -> None:
    mutation = decode_mutation('{"kind":"fact","seq":1,"fact":"label","targetId":"e1"}')

    assert isinstance(mutation, LabelFactMutation)
    assert mutation.label is None


def test_lane_mutation_round_trips_a_null_leaf() -> None:
    mutation = LaneMutation(seq=1, lane="thread", leaf_id=None)

    line = encode_mutation(mutation)

    assert json.loads(line)["leafId"] is None
    assert decode_mutation(line) == mutation


def test_parse_mutation_is_an_alias_for_decode_mutation() -> None:
    line = '{"kind":"lane","seq":1,"lane":"main","leafId":"e1"}'

    assert parse_mutation(line) == decode_mutation(line)


def test_refuses_to_encode_an_unsupported_mutation() -> None:
    class _Alien:
        kind = "alien"

    with pytest.raises(TypeError):
        encode_mutation(_Alien())


def test_encoded_lines_stay_single_line_for_multiline_and_unicode_text() -> None:
    # JSONL framing depends on the encoder escaping every embedded newline; a
    # raw newline in a message would split one entry across two log lines.
    text = 'line one\nline two\ttabbed "quoted" \\ backslash \r\nemoji 🙂 中文'
    entry = MessageEntry(id="e1", message=UserMessage(content=text, timestamp=1), parent_id=None, seq=1, timestamp=1)

    line = encode_mutation(EntryMutation(entry=entry, lane="main"))

    assert line.endswith("\n")
    assert line.count("\n") == 1
    assert "\r" not in line[:-1]
    assert decode_mutation(line).entry.message.content == text


def test_decodes_unicode_written_without_escape_sequences() -> None:
    # `JSON.stringify` leaves non-ASCII characters raw, so a TypeScript-written
    # line contains the literal characters rather than \uXXXX escapes.
    line = json.dumps(
        {
            "kind": "entry",
            "lane": "main",
            "type": "message",
            "id": "e1",
            "message": {"role": "user", "content": "héllo 🙂 中文", "timestamp": 1},
            "parentId": None,
            "seq": 1,
            "timestamp": 1,
        },
        ensure_ascii=False,
    )

    assert "🙂" in line
    assert decode_mutation(line).entry.message.content == "héllo 🙂 中文"


def test_empty_string_fields_survive_a_round_trip() -> None:
    entry = MessageEntry(
        id="e1",
        message=ToolResultMessage(
            tool_call_id="", tool_name="", content=[TextContent(text="")], is_error=False, timestamp=0
        ),
        parent_id=None,
        seq=1,
        timestamp=0,
    )

    payload = _entry_line(entry)

    assert payload["message"]["toolCallId"] == ""
    assert payload["message"]["content"][0]["text"] == ""
    _round_trip_entry(entry)


def test_model_change_entry_round_trips() -> None:
    entry = ModelChangeEntry(id="e1", provider="openai", model_id="gpt-5", parent_id="e0", seq=2, timestamp=3)

    payload = _entry_line(entry)

    assert payload["provider"] == "openai"
    assert payload["modelId"] == "gpt-5"
    _round_trip_entry(entry)


def test_compaction_intent_omits_absent_custom_instructions() -> None:
    record = OperationStartedRecord(
        id="run-5",
        lane="main",
        source_leaf_id=None,
        intent=CompactionIntent(result_entry_id="e-result"),
        seq=1,
        timestamp=10,
    )

    payload = json.loads(encode_mutation(RecordMutation(record=record)))

    assert payload["intent"] == {"kind": "compaction", "resultEntryId": "e-result"}
    _round_trip_record(record)


def test_label_fact_set_round_trips() -> None:
    mutation = LabelFactMutation(seq=1, target_id="e1", label="checkpoint")

    line = encode_mutation(mutation)

    assert json.loads(line)["label"] == "checkpoint"
    assert decode_mutation(line) == mutation


def test_refuses_to_encode_an_unsupported_message() -> None:
    class _Alien:
        role = "alien"

    entry = MessageEntry(id="e1", message=_Alien(), parent_id=None, seq=1, timestamp=1)

    with pytest.raises(TypeError):
        encode_mutation(EntryMutation(entry=entry, lane="main"))
