"""Render the agent telemetry schema reference.

Python port of `packages/agent/scripts/generate-telemetry-docs.ts`.

Usage:
    uv run python packages/pi-agent/scripts/generate_telemetry_docs.py
    uv run python packages/pi-agent/scripts/generate_telemetry_docs.py --check
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

from pi_agent.harness.telemetry import (
    AI_TELEMETRY_SCHEMA,
    HARNESS_TELEMETRY_SCHEMA,
    TelemetrySchemaDefinition,
)

AttributeDefinition = dict[str, Any]


def escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def allowed_values(definition: AttributeDefinition) -> str:
    if definition.get("values"):
        return ", ".join(str(value) for value in definition["values"])
    if definition.get("elementValues"):
        return "elements: " + ", ".join(str(value) for value in definition["elementValues"])
    return ""


def attribute_notes(definition: AttributeDefinition) -> str:
    notes = [
        f"{definition['cardinality']} cardinality" if definition.get("cardinality") else "",
        "sensitive" if definition.get("sensitive") else "",
    ]
    return ", ".join(note for note in notes if note)


def parent_description(parent: dict[str, Any]) -> str:
    kind = parent["kind"]
    if kind == "any":
        return "root or any caller span"
    if kind == "root_or_external":
        return "root or caller-owned external span"
    return ", ".join(f"`{span}`" for span in parent["spans"])


def render_schema(schema: TelemetrySchemaDefinition, title: str) -> list[str]:
    lines = [f"## {title}", "", f"Schema version: {schema['version']}", ""]
    for span_name, span in schema["spans"].items():
        lines += [f"### `{span_name}`", "", span["description"], ""]
        lines.append(f"- Parents: {parent_description(span['parents'])}")
        lines.append(f"- Default status: `{span['status']['default']}`")
        lines += [f"- Error when: {span['status']['errorWhen']}", ""]
        lines += ["#### Start attributes", ""]
        lines.append("| Name | Type | Required | Values | Notes | Description |")
        lines.append("|---|---|---:|---|---|---|")
        for name, definition in span["startAttributes"].items():
            required = "yes" if definition.get("required") else "no"
            lines.append(
                f"| `{name}` | `{definition['type']}` | {required} | {escape_cell(allowed_values(definition))} "
                f"| {escape_cell(attribute_notes(definition))} | {escape_cell(definition['description'])} |"
            )
        if not span["startAttributes"]:
            lines.append("| _none_ | | | | | |")
        lines += ["", "#### End attributes", ""]
        lines += ["All end attributes are optional completion enrichment.", ""]
        lines.append("| Name | Type | Values | Notes | Description |")
        lines.append("|---|---|---|---|---|")
        for name, definition in span["endAttributes"].items():
            lines.append(
                f"| `{name}` | `{definition['type']}` | {escape_cell(allowed_values(definition))} "
                f"| {escape_cell(attribute_notes(definition))} | {escape_cell(definition['description'])} |"
            )
        if not span["endAttributes"]:
            lines.append("| _none_ | | | | |")
        lines += ["", "#### Events", ""]
        events = list(span.get("events", {}).items())
        if not events:
            lines += ["No declared span events.", ""]
            continue
        for event_name, event in events:
            lines += [f"##### `{event_name}`", "", event["description"], ""]
            lines.append("| Name | Type | Required | Values | Notes | Description |")
            lines.append("|---|---|---:|---|---|---|")
            for name, definition in event["attributes"].items():
                required = "yes" if definition.get("required") else "no"
                lines.append(
                    f"| `{name}` | `{definition['type']}` | {required} | {escape_cell(allowed_values(definition))} "
                    f"| {escape_cell(attribute_notes(definition))} | {escape_cell(definition['description'])} |"
                )
            if not event["attributes"]:
                lines.append("| _none_ | | | | | |")
            lines.append("")
    return lines


def render_agent_telemetry_schema_markdown() -> str:
    lines = [
        "# Pi Agent Telemetry Schemas",
        "",
        "<!-- Generated by generate-telemetry-docs.ts. Do not edit manually. -->",
        "",
        *render_schema(AI_TELEMETRY_SCHEMA, "AI request schema"),
        *render_schema(HARNESS_TELEMETRY_SCHEMA, "Harness schema"),
    ]
    return "\n".join(lines).rstrip() + "\n"


def generate_telemetry_docs(output_path: Path, check: bool) -> None:
    expected = render_agent_telemetry_schema_markdown()
    if check:
        try:
            actual = output_path.read_text(encoding="utf-8")
        except OSError as error:
            raise RuntimeError(f"{output_path} is missing; run the telemetry documentation generator") from error
        if actual != expected:
            raise RuntimeError(f"{output_path} is stale; run the telemetry documentation generator")
        return
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(expected, encoding="utf-8")


DOCS_PATH = Path(__file__).resolve().parent.parent / "docs" / "telemetry-schema.md"


if __name__ == "__main__":
    generate_telemetry_docs(DOCS_PATH, "--check" in sys.argv)
