"""Agent harness: session storage and related infrastructure.

Python port of `packages/agent/src/harness/`. See `pi_agent.harness.session`
for the Entry/Record model, `SessionState` projection, and the in-memory and
JSONL v4 backends.

This module re-exports the runtime pieces ported alongside the session
layer: transcript truncation and shell-output capture (`utils/`), harness
message shapes and LLM conversion (`messages.py`), the event bus
(`events.py`), generic result/tagged-error helpers (`result.py`), the
system-prompt skills block (`system_prompt.py`), prompt-template and skill
discovery (`prompt_templates.py`, `skills.py`), shared harness types
(`types.py`), compaction and branch summarization (`compaction/`), and lane
state reduction (`reducer.py`).

`agent_harness.py` ports the durable multi-lane harness facade; see that
module's docstring for why most of its operations raise
`HarnessNotImplemented` (upstream does the same).

`pi_agent.harness.result` also defines a generic `Result` type (ported from
`result.ts`, which predates and duplicates the `Result` in `types.ts`).
`pi_agent.harness.types.Result` is the one used throughout this port (see
that module's docstring); `result.py`'s equivalent is re-exported here as
`GenericResult` to avoid shadowing it.
"""

from __future__ import annotations

from . import compaction, env, tools
from .agent_harness import (
    AgentHarness,
    AgentHarnessOptions,
    AgentLane,
    HarnessClosed,
    HarnessFault,
    HarnessNotImplemented,
    HarnessTool,
    LaneInfo,
    LaneSnapshot,
    NavigateOptions,
    OperationError,
    SessionSnapshot,
    SuspendedOperation,
)
from .events import (
    HarnessEvent,
    HarnessEventBus,
    HarnessEventListener,
    HarnessEventType,
    RunEndEvent,
    RunStartEvent,
    WatchHandle,
)
from .messages import (
    BRANCH_SUMMARY_PREFIX,
    BRANCH_SUMMARY_SUFFIX,
    COMPACTION_SUMMARY_PREFIX,
    COMPACTION_SUMMARY_SUFFIX,
    BashExecutionMessage,
    BranchSummaryMessage,
    CompactionSummaryMessage,
    CustomMessage,
    HarnessMessage,
    bash_execution_to_text,
    convert_to_llm,
    create_branch_summary_message,
    create_compaction_summary_message,
    create_custom_message,
)
from .prompt_templates import (
    PromptTemplateDiagnostic,
    PromptTemplateDiagnosticCode,
    SourcedPromptTemplate,
    SourcedPromptTemplateDiagnostic,
    format_prompt_template_invocation,
    load_prompt_templates,
    load_sourced_prompt_templates,
    parse_command_args,
    substitute_args,
)
from .reducer import (
    EffectiveLaneConfiguration,
    LaneModelConfig,
    LaneOperationState,
    LaneReductionInput,
    LaneReductionResult,
    LaneState,
    LaneStepState,
    NewestOwnEntry,
    OperationTargets,
    RecordLogCorruption,
    RecordLogCorruptionReason,
    RecordLogSlice,
    TerminalFailureState,
    ToolBatchCall,
    ToolBatchState,
    reduce_lane_state,
    validate_record_log,
)
from .result import ErrorMatchers, ResultNamespace, TaggedError, TaggedErrorValue, match_error
from .result import Result as GenericResult
from .skills import (
    SkillDiagnostic,
    SkillDiagnosticCode,
    SourcedSkill,
    SourcedSkillDiagnostic,
    format_skill_invocation,
    load_skills,
    load_sourced_skills,
)
from .system_prompt import format_skills_for_system_prompt
from .telemetry import (
    AGENT_TELEMETRY_SCHEMAS,
    AI_TELEMETRY_SCHEMA,
    HARNESS_TELEMETRY_SCHEMA,
    TelemetrySchemaDefinition,
    create_agent_span_starter,
    span_names,
    start_ai_span,
    start_harness_span,
)
from .types import (
    AgentHarnessResources,
    AgentHarnessStreamOptions,
    AgentHarnessStreamOptionsPatch,
    AgentHarnessTool,
    AgentHarnessToolContextSource,
    BranchSummaryError,
    BranchSummaryErrorCode,
    CompactionError,
    CompactionErrorCode,
    ExecutionEnv,
    ExecutionError,
    ExecutionErrorCode,
    FileError,
    FileErrorCode,
    FileInfo,
    FileKind,
    FileSystem,
    PromptTemplate,
    Result,
    Shell,
    ShellExecOptions,
    ShellExecResult,
    Skill,
    err,
    get_or_throw,
    get_or_undefined,
    ok,
    to_error,
)
from .utils import (
    DEFAULT_MAX_BYTES,
    DEFAULT_MAX_LINES,
    GREP_MAX_LINE_LENGTH,
    ShellCaptureOptions,
    ShellCaptureProgress,
    ShellCaptureResult,
    TruncatedLine,
    TruncationResult,
    execute_shell_with_capture,
    format_size,
    sanitize_binary_output,
    truncate_head,
    truncate_line,
    truncate_tail,
)

__all__ = [
    "AGENT_TELEMETRY_SCHEMAS",
    "AI_TELEMETRY_SCHEMA",
    "BRANCH_SUMMARY_PREFIX",
    "BRANCH_SUMMARY_SUFFIX",
    "COMPACTION_SUMMARY_PREFIX",
    "COMPACTION_SUMMARY_SUFFIX",
    "DEFAULT_MAX_BYTES",
    "DEFAULT_MAX_LINES",
    "GREP_MAX_LINE_LENGTH",
    "HARNESS_TELEMETRY_SCHEMA",
    "AgentHarness",
    "AgentHarnessOptions",
    "AgentHarnessResources",
    "AgentHarnessStreamOptions",
    "AgentHarnessStreamOptionsPatch",
    "AgentHarnessTool",
    "AgentHarnessToolContextSource",
    "AgentLane",
    "BashExecutionMessage",
    "BranchSummaryError",
    "BranchSummaryErrorCode",
    "BranchSummaryMessage",
    "CompactionError",
    "CompactionErrorCode",
    "CompactionSummaryMessage",
    "CustomMessage",
    "EffectiveLaneConfiguration",
    "ErrorMatchers",
    "ExecutionEnv",
    "ExecutionError",
    "ExecutionErrorCode",
    "FileError",
    "FileErrorCode",
    "FileInfo",
    "FileKind",
    "FileSystem",
    "GenericResult",
    "HarnessClosed",
    "HarnessEvent",
    "HarnessEventBus",
    "HarnessEventListener",
    "HarnessEventType",
    "HarnessFault",
    "HarnessMessage",
    "HarnessNotImplemented",
    "HarnessTool",
    "LaneInfo",
    "LaneModelConfig",
    "LaneOperationState",
    "LaneReductionInput",
    "LaneReductionResult",
    "LaneSnapshot",
    "LaneState",
    "LaneStepState",
    "NavigateOptions",
    "NewestOwnEntry",
    "OperationError",
    "OperationTargets",
    "PromptTemplate",
    "PromptTemplateDiagnostic",
    "PromptTemplateDiagnosticCode",
    "RecordLogCorruption",
    "RecordLogCorruptionReason",
    "RecordLogSlice",
    "Result",
    "ResultNamespace",
    "RunEndEvent",
    "RunStartEvent",
    "SessionSnapshot",
    "Shell",
    "ShellCaptureOptions",
    "ShellCaptureProgress",
    "ShellCaptureResult",
    "ShellExecOptions",
    "ShellExecResult",
    "Skill",
    "SkillDiagnostic",
    "SkillDiagnosticCode",
    "SourcedPromptTemplate",
    "SourcedPromptTemplateDiagnostic",
    "SourcedSkill",
    "SourcedSkillDiagnostic",
    "SuspendedOperation",
    "TaggedError",
    "TaggedErrorValue",
    "TelemetrySchemaDefinition",
    "TerminalFailureState",
    "ToolBatchCall",
    "ToolBatchState",
    "TruncatedLine",
    "TruncationResult",
    "WatchHandle",
    "bash_execution_to_text",
    "compaction",
    "convert_to_llm",
    "create_agent_span_starter",
    "create_branch_summary_message",
    "create_compaction_summary_message",
    "create_custom_message",
    "env",
    "err",
    "execute_shell_with_capture",
    "format_prompt_template_invocation",
    "format_size",
    "format_skill_invocation",
    "format_skills_for_system_prompt",
    "get_or_throw",
    "get_or_undefined",
    "load_prompt_templates",
    "load_skills",
    "load_sourced_prompt_templates",
    "load_sourced_skills",
    "match_error",
    "ok",
    "parse_command_args",
    "reduce_lane_state",
    "sanitize_binary_output",
    "span_names",
    "start_ai_span",
    "start_harness_span",
    "substitute_args",
    "to_error",
    "tools",
    "truncate_head",
    "truncate_line",
    "truncate_tail",
    "validate_record_log",
]
